version: '2.1'
services:
  develop-elasticsearch:
    build:
      args:
        - IMAGE_ARG_ES_IMAGE_NAME=${IMAGE_ARG_ES_IMAGE_NAME:-elasticsearch-oss} #elasticsearch-oss
        - IMAGE_ARG_ES_IMAGE_VERSION=${IMAGE_ARG_ES_IMAGE_VERSION:-7.4.0} #5.6.10
      context: .
      dockerfile: Dockerfile
    cap_add:
      - IPC_LOCK
    container_name: ${CONTAINER_HOST_NAME:-standalone.elk}-elasticsearch
    environment:
      action.destructive_requires_name: 'true'
      bootstrap.memory_lock: ${ELASTICSEARCH_BOOTSTRAP_MEMORYLOCK:-true}
      cluster.name: ${ELASTICSEARCH_CLUSTER_NAME:-standalone.elk-elasticsearch}
      discovery.type: ${ELASTICSEARCH_DISCOVERY_TYPE:-single-node}
      http.host: ${ELASTICSEARCH_HTTP_HOST:-0.0.0.0}
      http.port: ${ELASTICSEARCH_HTTP_PORT:-9200}
      indices.memory.index_buffer_size: 512M
      indices.memory.max_index_buffer_size: 512M
      indices.query.bool.max_clause_count: 8192
      #network.host: ${ELASTICSEARCH_NETWORK_HOST:_non_loopback_}
      network.host: ${ELASTICSEARCH_NETWORK_HOST:-0.0.0.0}
      network.publish_host: ${ELASTICSEARCH_NETWORK_PUBLISHHOST:-172.16.238.62}
      search.max_buckets: ${ELASTICSEARCH_SEARCH_MAX_BUCKETS:-2147483647}
      transport.host: ${ELASTICSEARCH_TRANSPORT_HOST:-localhost}
      transport.publish_host: ${ELASTICSEARCH_TRANSPORT_PUBLISHHOST:-localhost}
      transport.publish_port: ${ELASTICSEARCH_TRANSPORT_PUBLISHPORT:-9300}
      transport.tcp.port: ${ELASTICSEARCH_TRANSPORT_TCP_PORT:-9300}
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      #xpack.security.enabled: ${ELASTICSEARCH_XPACK_SECURITY_ENABLED:-false}
      ES_JAVA_OPTS: ${ES_JAVA_OPTS:--Xms1024m -Xmx2048m}
    hostname: ${CONTAINER_HOST_NAME:-standalone.elk}-elasticsearch
    image: cirepo/${IMAGE_ARG_ES_IMAGE_NAME:-elasticsearch-oss}:${IMAGE_TAG:-7.4.0} #5.6.10
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.elk-elasticsearch}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/elk-elasticsearch/standalone}
    #mem_limit: ${MEM_LIMIT:-1g}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.62}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::62}
    ports:
      - ${EXTERNAL_ES_HTTP_9200_PORT:-9200}:${ELASTICSEARCH_HTTP_PORT:-9200}
      - ${EXTERNAL_ES_TRANSPORT_TCP_9300_PORT:-9300}:${ELASTICSEARCH_TRANSPORT_TCP_PORT:-9300}
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data:/usr/share/elasticsearch/data

networks:
  local-network:
    external: true
    driver_opts:
      com.docker.network.driver.mtu: 1450
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - gateway: 172.16.238.1
        - subnet: 172.16.238.0/24
        #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
