version: '2.1'
services:
  develop-elasticsearch:
    build:
      args:
        - IMAGE_ARG_ES_IMAGE_NAME=${IMAGE_ARG_ES_IMAGE_NAME:-elasticsearch} #elasticsearch-oss
        - IMAGE_ARG_ES_IMAGE_VERSION=${IMAGE_ARG_ES_IMAGE_VERSION:-7.5.1} #5.6.10
      context: .
      dockerfile: Dockerfile
    cap_add:
      - IPC_LOCK
    #command: ${ELASTICSEARCH_COMMAND:-elasticsearch}
    container_name: ${CONTAINER_HOST_NAME:-standalone.elk}-elasticsearch
    environment:
      action.destructive_requires_name: 'true'
      bootstrap.memory_lock: ${ELASTICSEARCH_BOOTSTRAP_MEMORYLOCK:-true}
      cluster.name: ${ELASTICSEARCH_CLUSTER_NAME:-standalone.elk-elasticsearch}
      discovery.type: ${ELASTICSEARCH_DISCOVERY_TYPE:-single-node}
      http.compression: ${ELASTICSEARCH_HTTP_COMPRESSION:-true}
      http.compression_level: ${ELASTICSEARCH_HTTP_COMPRESSION_LEVEL:-5}
      http.host: ${ELASTICSEARCH_HTTP_HOST:-0.0.0.0}
      http.port: ${ELASTICSEARCH_HTTP_PORT:-9200}
      indices.memory.index_buffer_size: ${ELASTICSEARCH_INDICES_MEMORY_INDEX_BUFFER_SIZE:-30%}
      indices.memory.max_index_buffer_size: ${ELASTICSEARCH_INDICES_MEMORY_MAX_INDEX_BUFFER_SIZE:-3g}
      indices.query.bool.max_clause_count: ${INDICES_QUERY_BOOL_MAX_CLAUSE_COUNT:-8192}
      logger.level: ${LOGGER_LEVEL:-INFO}
      #network.host: ${ELASTICSEARCH_NETWORK_HOST:_non_loopback_}
      network.host: ${ELASTICSEARCH_NETWORK_HOST:-0.0.0.0}
      network.publish_host: ${ELASTICSEARCH_NETWORK_PUBLISHHOST:-172.16.238.62}
      #node.attr.box_type: ${ELASTICSEARCH_NODE_ATTR_BOX_TYPE:-hot}
      search.max_buckets: ${ELASTICSEARCH_SEARCH_MAX_BUCKETS:-2147483647}
      search.max_open_scroll_context: ${ELASTICSEARCH_SEARCH_MAX_OPEN_SCROLL_CONTEXT:-2147483647}
      thread_pool.write.size: ${ELASTICSEARCH_THREAD_POOL_WRITE_SIZE:-2}
      thread_pool.write.queue_size: ${ELASTICSEARCH_THREAD_POOL_WRITE_QUEUE_SIZE:-1000}
      #transport.cname_in_publish_address: ${ELASTICSEARCH_TRANSPORT_CNAME_IN_PUBLISH_ADDRESS:-true}
      transport.host: ${ELASTICSEARCH_TRANSPORT_HOST:-localhost}
      transport.publish_host: ${ELASTICSEARCH_TRANSPORT_PUBLISHHOST:-localhost}
      transport.publish_port: ${ELASTICSEARCH_TRANSPORT_PUBLISHPORT:-9300}
      transport.tcp.port: ${ELASTICSEARCH_TRANSPORT_TCP_PORT:-9300}
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      xpack.security.enabled: ${XPACK_SECURITY_ENABLED:-false}
      ES_JAVA_OPTS: ${ES_JAVA_OPTS:--Xms5120m -Xmx5120m}
    hostname: ${CONTAINER_HOST_NAME:-standalone.elk}-elasticsearch
    image: cirepo/${IMAGE_ARG_ES_IMAGE_NAME:-elasticsearch}:${IMAGE_TAG:-7.5.1} #5.6.10
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.elk-elasticsearch}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/elk-elasticsearch/standalone}
    mem_limit: ${MEM_LIMIT:-10g}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.62}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::62}
    ports:
      - ${EXTERNAL_ES_HTTP_9200_PORT:-9200}:${ELASTICSEARCH_HTTP_PORT:-9200}
      - ${EXTERNAL_ES_TRANSPORT_TCP_9300_PORT:-9300}:${ELASTICSEARCH_TRANSPORT_TCP_PORT:-9300}
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data:/usr/share/elasticsearch/data

#  # docker run --network local-network --ip 172.16.238.61 -p 5000:5000 elastichq/elasticsearch-hq
#  develop-elasticsearch-hq:
#    container_name: ${CONTAINER_HOST_NAME:-standalone.elk}-elasticsearch-hq
#    environment:
#      HQ_DEFAULT_URL: ${HQ_DEFAULT_URL:-http://standalone.elk-elasticsearch:9200}
#      HQ_ENABLE_SSL: ${HQ_ENABLE_SSL:-false}
#    hostname: ${CONTAINER_HOST_NAME:-standalone.elk}-elasticsearch-hq
#    image: elastichq/elasticsearch-hq:release-v3.5.4
#    networks:
#      local-network:
#        ipv4_address: ${IPV4_ADDRESS:-172.16.238.61}
#    ports:
#      - ${EXTERNAL_ES_HQ_HTTP_5000_PORT:-5000}:5000
#    restart: always

networks:
  local-network:
    external: true
    driver_opts:
      com.docker.network.driver.mtu: 1450
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - gateway: 172.16.238.1
        - subnet: 172.16.238.0/24
        #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
