version: '2.1'
services:
  develop-elasticsearch:
    build:
      args:
        - IMAGE_ARG_ES_IMAGE_NAME=${IMAGE_ARG_ES_IMAGE_NAME:-elasticsearch} #elasticsearch-oss
        - IMAGE_ARG_ES_IMAGE_VERSION=${IMAGE_ARG_ES_IMAGE_VERSION:-6.8.6} #5.6.10
      context: .
      dockerfile: Dockerfile
    cap_add:
      - IPC_LOCK
    #command: ${ELASTICSEARCH_COMMAND:-elasticsearch}
    container_name: ${CONTAINER_HOST_NAME:-standalone.elk}-elasticsearch
    environment:
      ELASTICSEARCH_ACTION_DESTRUCTIVE_REQUIRES_NAME: 'true'
      ELASTICSEARCH_BOOTSTRAP_MEMORYLOCK: ${ELASTICSEARCH_BOOTSTRAP_MEMORYLOCK:-true}
      ELASTICSEARCH_CLUSTER_NAME: ${ELASTICSEARCH_CLUSTER_NAME:-standalone.elk-elasticsearch}
      ELASTICSEARCH_DISCOVERY_TYPE: ${ELASTICSEARCH_DISCOVERY_TYPE:-single-node}
      ELASTICSEARCH_HTTP_COMPRESSION: ${ELASTICSEARCH_HTTP_COMPRESSION:-true}
      ELASTICSEARCH_HTTP_COMPRESSION_LEVEL: ${ELASTICSEARCH_HTTP_COMPRESSION_LEVEL:-5}
      ELASTICSEARCH_HTTP_HOST: ${ELASTICSEARCH_HTTP_HOST:-0.0.0.0}
      ELASTICSEARCH_HTTP_MAX_CONTENT_LENGTH: ${ELASTICSEARCH_HTTP_MAX_CONTENT_LENGTH:-1024mb}
      ELASTICSEARCH_HTTP_MAX_HEADER_SIZE: ${ELASTICSEARCH_HTTP_MAX_HEADER_SIZE:-1mb}
      ELASTICSEARCH_HTTP_MAX_INITIAL_LINE_LENGTH: ${ELASTICSEARCH_HTTP_MAX_INITIAL_LINE_LENGTH:-16kb}
      ELASTICSEARCH_HTTP_PORT: ${ELASTICSEARCH_HTTP_PORT:-9200}
      ELASTICSEARCH_INDICES_MEMORY_INDEX_BUFFER_SIZE: ${ELASTICSEARCH_INDICES_MEMORY_INDEX_BUFFER_SIZE:-30%}
      ELASTICSEARCH_INDICES_MEMORY_MAX_INDEX_BUFFER_SIZE: ${ELASTICSEARCH_INDICES_MEMORY_MAX_INDEX_BUFFER_SIZE:-3g}
      ELASTICSEARCH_INDICES_QUERY_BOOL_MAX_CLAUSE_COUNT: ${ELASTICSEARCH_INDICES_QUERY_BOOL_MAX_CLAUSE_COUNT:-8192}
      LOGGER_LEVEL: ${LOGGER_LEVEL:-INFO}
      ELASTICSEARCH_NETWORK_HOST: ${ELASTICSEARCH_NETWORK_HOST:-0.0.0.0} #network.host: _non_loopback_
      ELASTICSEARCH_NETWORK_PUBLISHHOST: ${ELASTICSEARCH_NETWORK_PUBLISHHOST:-172.16.238.62}
      #ELASTICSEARCH_NODE_ATTR_BOX_TYPE: ${ELASTICSEARCH_NODE_ATTR_BOX_TYPE:-hot}
      path.logs: '/var/log/elasticsearch'
      ELASTICSEARCH_SEARCH_MAX_BUCKETS: ${ELASTICSEARCH_SEARCH_MAX_BUCKETS:-2147483647}
      ELASTICSEARCH_SEARCH_MAX_OPEN_SCROLL_CONTEXT: ${ELASTICSEARCH_SEARCH_MAX_OPEN_SCROLL_CONTEXT:-2147483647}
      ELASTICSEARCH_THREAD_POOL_WRITE_QUEUE_SIZE: ${ELASTICSEARCH_THREAD_POOL_WRITE_QUEUE_SIZE:-1000}
      ELASTICSEARCH_THREAD_POOL_WRITE_SIZE: ${ELASTICSEARCH_THREAD_POOL_WRITE_SIZE:-2}
      #ELASTICSEARCH_TRANSPORT_CNAME_IN_PUBLISH_ADDRESS: ${ELASTICSEARCH_TRANSPORT_CNAME_IN_PUBLISH_ADDRESS:-true} # suppress warning: transport.publish_address was printed as [ip:port] instead of [hostname/ip:port]. This format is deprecated and will change to [hostname/ip:port] in a future version. Use -Des.transport.cname_in_publish_address=true to enforce non-deprecated formatting.
      ELASTICSEARCH_TRANSPORT_HOST: ${ELASTICSEARCH_TRANSPORT_HOST:-localhost}
      ELASTICSEARCH_TRANSPORT_PUBLISHHOST: ${ELASTICSEARCH_TRANSPORT_PUBLISHHOST:-localhost}
      ELASTICSEARCH_TRANSPORT_PUBLISHPORT: ${ELASTICSEARCH_TRANSPORT_PUBLISHPORT:-9300}
      ELASTICSEARCH_TRANSPORT_TCP_PORT: ${ELASTICSEARCH_TRANSPORT_TCP_PORT:-9300}
      ELASTICSEARCH_XPACK_SECURITY_ENABLED: ${ELASTICSEARCH_XPACK_SECURITY_ENABLED:-false} # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      ES_JAVA_OPTS: ${ES_JAVA_OPTS:--Xms5120m -Xmx5120m}
    hostname: ${CONTAINER_HOST_NAME:-standalone.elk}-elasticsearch
    image: cirepo/${IMAGE_ARG_ES_IMAGE_NAME:-elasticsearch}:${IMAGE_TAG:-6.8.6} #5.6.10
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.elk-elasticsearch}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/elk-elasticsearch/standalone}
    mem_limit: ${MEM_LIMIT:-10g}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.62}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::62}
    ports:
      - ${EXTERNAL_ES_HTTP_9200_PORT:-9200}:${ELASTICSEARCH_HTTP_PORT:-9200}
      - ${EXTERNAL_ES_TRANSPORT_TCP_9300_PORT:-9300}:${ELASTICSEARCH_TRANSPORT_TCP_PORT:-9300}
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
#      - filebeat-config:/etc/filebeat
#      - metricbeat-config:/etc/metricbeat

#  # docker run --network local-network --ip 172.16.238.61 -p 5000:5000 elastichq/elasticsearch-hq
#  develop-elasticsearch-hq:
#    container_name: ${CONTAINER_HOST_NAME:-standalone.elk}-elasticsearch-hq
#    environment:
#      HQ_DEFAULT_URL: ${HQ_DEFAULT_URL:-http://standalone.elk-elasticsearch:9200}
#      HQ_ENABLE_SSL: ${HQ_ENABLE_SSL:-false}
#    hostname: ${CONTAINER_HOST_NAME:-standalone.elk}-elasticsearch-hq
#    image: elastichq/elasticsearch-hq:release-v3.5.4
#    networks:
#      local-network:
#        ipv4_address: ${IPV4_ADDRESS:-172.16.238.61}
#    ports:
#      - ${EXTERNAL_ES_HQ_HTTP_5000_PORT:-5000}:5000
#    restart: always

networks:
  local-network:
    external: true
    driver_opts:
      com.docker.network.driver.mtu: 1450
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - gateway: 172.16.238.1
        - subnet: 172.16.238.0/24
        #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/usr/share/elasticsearch/data
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/var/log/elasticsearch
      o: bind
  filebeat-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/etc/filebeat
      o: bind
  metricbeat-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/etc/metricbeat
      o: bind
