
version: '2.1'
services:
  elasticsearch-standalone-develop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch-standalone
    environment:
    - bootstrap.memory_lock=true
    - cluster.name=elasticsearch-standalone
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    hostname: elasticsearch-standalone
    image: cirepo/elasticsearch-oss:${IMAGE_TAG:-5.6.10} #6.2.3
    networks:
      local-network:
        ipv4_address: 172.16.238.62
        ipv6_address: 2001:3984:3989::62
    ports:
    - 9200:9200
    - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      - subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
