
version: '2.1'
services:
  elasticsearch-standalone-develop:
    build:
      args:
      - IMAGE_ARG_ES_IMAGE_NAME=${IMAGE_ARG_ES_IMAGE_NAME:-elasticsearch} #elasticsearch-oss
      - IMAGE_ARG_ES_IMAGE_VERSION=${IMAGE_ARG_ES_IMAGE_VERSION:-5.6.10} #6.2.3
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_HOST_NAME:-standalone.elasticsearch}
    environment:
    - bootstrap.memory_lock=true
    - cluster.name=elasticsearch-standalone
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    hostname: ${CONTAINER_HOST_NAME:-standalone.elasticsearch}
    image: cirepo/${IMAGE_ARG_ES_IMAGE_NAME:-elasticsearch}:${IMAGE_TAG:-5.6.10} #6.2.3
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.elasticsearch}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/elasticsearch/standalone}
    networks:
      local-network:
        ipv4_address: 172.16.238.62
        #ipv6_address: 2001:3984:3989::62
    ports:
    - 9200:9200
    - 9300:9300
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
